aiefal: rsc: added XAie_ModuleType cast & remove UserRsc
added casts to prevent this conversion error:
invalid conversion from ‘u32 {aka unsigned int}’ to ‘XAie_ModuleType’
casts were added to various functions and statements to avoid issue
also remove UserRsc class and fix remove R.Type
R.Type was inconsistent with enum definition in global
caused this issue in utest:
error: ‘struct XAie_UserRsc’ has no member named ‘Type’
global XAie_RscType only has XAIE_PERFCNT_RSC enum
also remove XAie_UserClass under xaiefal namespace caused
compilation error converting to global XAie_UserRsc:
error: cannot convert ‘xaiefal::XAie_UserRsc*’ to ‘XAie_UserRsc*’

Signed-off-by: Alex Kiani <alex.kiani@xilinx.com>
Acked-by: Wendy Liang <wendy.liang@xilinx.com>