Some Windows SDK results in build warning treated as error
Add target compile option disabling C4255.

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.27673.0\um\winuser.h(16145,1): error C2220: the following warning is treated as an error [...\src\aie_codegen.vcxproj]
  (compiling source file 'src/io_backend/ext/xaie_sim.c')

C:\Program Files (x86)\Windows Kits\10\Include\10.0.27673.0\um\winuser.h(16145,1): warning C4255: 'GetCurrentMonitorTopologyId': no function prototype given: converting '()' to '(void)' [...\src\aie_codegen.vcxproj]
  (compiling source file 'src/io_backend/ext/xaie_sim.c')
```

Added
```
target_compile_options(... PRIVATE /wd4255)
```

Please, consider fixing the code instead of disabling warnings.

SDK used is Windows SDK version 10.0.27673.0

Signed-off-by: Soren Soe <2106410+stsoe@users.noreply.github.com>